version: '3.8'

services:
  api:
    build:
      target: production
    command: node dist/main
    env_file:
      - .env.production
    volumes:
      - /usr/src/app/node_modules
    restart: always 