version: '3.8'

services:
  api:
    build:
      target: development
    command: pnpm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.development 